version: '3.1'
 
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    expose: 
      - 3306/tcp
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    networks:
      test_net:
        ipv4_address: 172.28.3.1
    environment:
      NODE_ENV: debug
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  wp:
    build:
      context: ./docker
      dockerfile: Dockerfile-WP
    ports:
      - 8080:80
    volumes:
      #- ./docker/php.conf.ini:/usr/local/etc/php/conf.d
      - ./app:/var/www/html
    depends_on:
      - db
    links:
      - db
    networks:
      test_net:
        ipv4_address: 172.28.3.2
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      XDEBUG_CONFIG: remote_host=10.254.254.254
      WP_DEBUG: 1
    volumes:
      - wp:/var/www/html
    restart: always
 
volumes:
  wp:
  db:
networks:
    test_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.3.0/16
